// Sinhala catalogue — first draft; have a native speaker review before usability testing.
// Keys are the English text exactly as written in the app (see lib/i18n.js).
// Placeholders like {amount} must appear in the Sinhala too; word order may change.
export default {
  "shop": "කඩය",
  "family": "පවුලේ සාමාජිකයා",
  "daughter": "දියණිය",
  "son": "පුතා",
  "A Sri Lankan mobile number has 10 digits, starting 07.": "ශ්‍රී ලාංකික ජංගම අංකයක 07 න් ආරම්භ වන ඉලක්කම් 10ක් ඇත.",
  "+ 1 more payment on the way": "+ තවත් ගෙවීමක් එමින් පවතී",
  "+ {n} more payments on the way": "+ තවත් ගෙවීම් {n}ක් එමින් පවතී",
  "1 day ago": "ඊයේ",
  "1 hour": "පැය 1",
  "1 offer · best {price}": "දීමනා 1 · හොඳම {price}",
  "1 try left.": "තව එක් උත්සාහයක් ඉතිරියි.",
  "10 kg+": "10 kg+",
  "100 kg+": "100 kg+",
  "2 days ago": "දින 2කට පෙර",
  "2-hour inspection window after arrival": "පැමිණි පසු පැය 2ක පරීක්ෂා කාලය",
  "3 days ago": "දින 3කට පෙර",
  "3. The delivery time is checked against the transporter’s record.": "3. භාරදුන් වේලාව ප්‍රවාහකයාගේ වාර්තාව සමඟ සසඳා බලයි.",
  "4. You do not need to telephone anyone.": "4. ඔබට කිසිවෙකුට දුරකථනයෙන් කතා කිරීමට අවශ්‍ය නැත.",
  "50 kg+": "50 kg+",
  "6-digit code": "ඉලක්කම් 6ක කේතය",
  "6-digit code · usually arrives within 60 seconds": "ඉලක්කම් 6ක කේතය · සාමාන්‍යයෙන් තත්පර 60ක් ඇතුළත ලැබේ",
  "A Sri Lankan mobile number starts with 07.": "ශ්‍රී ලාංකික ජංගම අංකයක් 07 න් ආරම්භ වේ.",
  "A family member, shop or field officer is entering details": "පවුලේ සාමාජිකයෙක්, කඩයක් හෝ ක්ෂේත්‍ර නිලධාරියෙක් විස්තර ඇතුළත් කරයි",
  "A transporter is being booked": "ප්‍රවාහකයෙකු වෙන් කරමින්",
  "A transporter is being booked for this collection": "මෙම එකතු කිරීම සඳහා ප්‍රවාහකයෙකු වෙන් කරමින්",
  "About your business": "ඔබේ ව්‍යාපාරය ගැන",
  "About {kg} kg": "ආසන්න වශයෙන් {kg} kg",
  "Accept offer": "දීමනාව පිළිගන්න",
  "Accept offer — needs internet": "දීමනාව පිළිගන්න — අන්තර්ජාලය අවශ්‍යයි",
  "Accept this job": "මෙම රැකියාව පිළිගන්න",
  "Accept — {amount}": "පිළිගන්න — {amount}",
  "Accepted": "පිළිගත්තා",
  "Account": "ගිණුම",
  "Account name: {name}": "ගිණුමේ නම: {name}",
  "Account number": "ගිණුම් අංකය",
  "Add photos — at least one": "ඡායාරූප එක් කරන්න — අවම වශයෙන් එකක්",
  "After 3 wrong codes": "වැරදි කේත 3කට පසු",
  "Agree a new time with {name} up to {time}": "{time} දක්වා {name} සමඟ නව වේලාවක් එකඟ වන්න",
  "Agreed with {buyer}": "{buyer} සමඟ එකඟ විය",
  "Agreement confirmed": "ගිවිසුම තහවුරුයි",
  "Agreement not found": "ගිවිසුම හමු නොවීය",
  "Agreement {id}": "ගිවිසුම {id}",
  "Agreement {id} — agro": "ගිවිසුම {id} — agro",
  "All crops": "සියලු බෝග",
  "All {kg} kg": "සියලු {kg} kg",
  "Already registered? Enter the same number — you will be signed in.": "දැනටමත් ලියාපදිංචිද? එම අංකයම ඇතුළත් කරන්න — ඔබ පිවිසෙනු ඇත.",
  "Also happening": "තවත් සිදුවන දේ",
  "Any date": "ඕනෑම දිනයක්",
  "Any qty": "ඕනෑම ප්‍රමාණයක්",
  "Arrived": "පැමිණියා",
  "Arriving today": "අද පැමිණේ",
  "Asked {price} · harvested {date}": "ඉල්ලූ මිල {price} · අස්වනු නෙළූයේ {date}",
  "At least one photo of the load on the scale.": "තරාදිය මත ඇති තොගයේ අවම වශයෙන් එක් ඡායාරූපයක්.",
  "Automatic if no one disputes": "කිසිවෙකු විරුද්ධ නොවුවහොත් ස්වයංක්‍රීයයි",
  "Available": "ලබා ගත හැකි",
  "Back": "ආපසු",
  "Back to jobs": "රැකියා වෙත ආපසු",
  "Back to search": "සෙවුමට ආපසු",
  "Bank": "බැංකුව",
  "Bank account": "බැංකු ගිණුම",
  "Bank transfer": "බැංකු හුවමාරුව",
  "Beans": "බෝංචි",
  "Beans guidance this week: Rs 170–205/kg": "මේ සතියේ බෝංචි මිල මඟපෙන්වීම: රු. 170–205/kg",
  "Being checked": "පරීක්ෂා කෙරේ",
  "Best offer pays you": "හොඳම දීමනාවෙන් ඔබට ලැබේ",
  "Booked": "වෙන් කර ඇත",
  "Booked after you accept": "ඔබ පිළිගත් පසු වෙන් කෙරේ",
  "Booking a lorry": "ලොරියක් වෙන් කරමින්",
  "Bulk collection": "තොග එකතු කිරීම",
  "Bulk collection from {name}": "{name}ගෙන් තොග එකතු කිරීම",
  "Business or buyer name": "ව්‍යාපාරයේ හෝ ගැනුම්කරුගේ නම",
  "Buyer": "ගැනුම්කරු",
  "Buyer pays transport": "ප්‍රවාහන ගාස්තුව ගැනුම්කරු ගෙවයි",
  "Buyers see the harvest date": "ගැනුම්කරුවන්ට අස්වනු දිනය පෙනේ",
  "Buyers will no longer see it. Offers already sent are cancelled.": "ගැනුම්කරුවන්ට එය තවදුරටත් නොපෙනේ. දැනටමත් එවූ දීමනා අවලංගු වේ.",
  "Buying all {kg} kg? Make an offer": "සියලු {kg} kg මිලදී ගන්නවාද? දීමනාවක් කරන්න",
  "Cabbage": "ගෝවා",
  "Call 0112 000 000 or ask a registered field officer to sign you in.": "0112 000 000 අමතන්න, නැතහොත් ලියාපදිංචි ක්ෂේත්‍ර නිලධාරියෙකුගෙන් ඔබව පිවිසවීමට ඉල්ලන්න.",
  "Can still change": "තවමත් වෙනස් කළ හැක",
  "Cancel": "අවලංගු කරන්න",
  "Cancel this order": "මෙම ඇණවුම අවලංගු කරන්න",
  "Cancelled": "අවලංගුයි",
  "Cannot reach the market": "වෙළඳපොළට සම්බන්ධ විය නොහැක",
  "Carrot": "කැරට්",
  "Case {id} · {date}, {time}": "නඩුව {id} · {date}, {time}",
  "Cash": "මුදලින්",
  "Cash at collection": "එකතු කරන විට මුදලින්",
  "Cash on collection": "එකතු කරන විට මුදලින්",
  "Change": "වෙනස් කරන්න",
  "Change phone number": "දුරකථන අංකය වෙනස් කරන්න",
  "Change to {kg} kg": "{kg} kg ලෙස වෙනස් කරන්න",
  "Changing where money goes later needs a code sent to this phone number.": "පසුව මුදල් යන තැන වෙනස් කිරීමට මෙම දුරකථන අංකයට එවන කේතයක් අවශ්‍යයි.",
  "Check and confirm": "පරීක්ෂා කර තහවුරු කරන්න",
  "Check the newest SMS — an older code will not work.": "අලුත්ම SMS එක බලන්න — පැරණි කේතයක් ක්‍රියා නොකරයි.",
  "Check the weight": "බර පරීක්ෂා කරන්න",
  "Check the {crop} within 2 hours of arrival. Your {amount} stays held until you confirm, or report a problem.": "පැමිණ පැය 2ක් ඇතුළත {crop} පරීක්ෂා කරන්න. ඔබ තහවුරු කරන තුරු හෝ ගැටලුවක් වාර්තා කරන තුරු ඔබේ {amount} රඳවා තබයි.",
  "Check this quantity": "මෙම ප්‍රමාණය පරීක්ෂා කරන්න",
  "Checking for new offers…": "නව දීමනා පරීක්ෂා කරමින්…",
  "Choose one to continue": "ඉදිරියට යාමට එකක් තෝරන්න",
  "Choose one. This only changes what the app shows you — you can add another role later.": "එකක් තෝරන්න. මෙයින් වෙනස් වන්නේ යෙදුම ඔබට පෙන්වන දේ පමණි — පසුව වෙනත් භූමිකාවක් එක් කළ හැක.",
  "Choose who is holding the phone.": "දුරකථනය තිබෙන්නේ කා අතදැයි තෝරන්න.",
  "Clear all": "සියල්ල ඉවත් කරන්න",
  "Clear all filters": "සියලු පෙරහන් ඉවත් කරන්න",
  "Close — finish later": "වසන්න — පසුව අවසන් කරන්න",
  "Collect from": "රැගෙන යන ස්ථානය",
  "Collected": "එකතු කළා",
  "Collected and on the way to {place}.": "එකතු කර {place} වෙත රැගෙන යමින්.",
  "Collected by": "රැගෙන යන්නේ",
  "Collected from the farm": "ගොවිපොළෙන් රැගෙන ගියා",
  "Collected · on the way": "එකතු කළා · මඟ දිගේ",
  "Collected — check the weight": "එකතු කළා — බර පරීක්ෂා කරන්න",
  "Collection": "එකතු කිරීම",
  "Collection & payout": "එකතු කිරීම සහ ගෙවීම",
  "Collection area": "එකතු කිරීමේ ප්‍රදේශය",
  "Collection time — {time}": "එකතු කරන වේලාව — {time}",
  "Collection window": "එකතු කිරීමේ කාලය",
  "Collection: {time} · transport paid by buyer": "එකතු කිරීම: {time} · ප්‍රවාහනය ගැනුම්කරු ගෙවයි",
  "Coming to you": "ඔබට ලැබෙන්නට ඇති",
  "Compare offers and see what you receive after fees": "දීමනා සසඳා ගාස්තු අඩු කළ පසු ලැබෙන මුදල බලන්න",
  "Compare {n} offers": "දීමනා {n}ක් සසඳන්න",
  "Confirm": "තහවුරු කරන්න",
  "Confirm code": "කේතය තහවුරු කරන්න",
  "Confirm collection": "එකතු කිරීම තහවුරු කරන්න",
  "Confirm order received": "ඇණවුම ලැබුණු බව තහවුරු කරන්න",
  "Confirm {kg} kg": "{kg} kg තහවුරු කරන්න",
  "Confirmed": "තහවුරුයි",
  "Confirmed {date}, {time} · Agreement no. {id}": "තහවුරු කළේ {date}, {time} · ගිවිසුම් අංකය {id}",
  "Continue as a buyer": "ගැනුම්කරුවෙකු ලෙස ඉදිරියට",
  "Continue as a farmer": "ගොවියෙකු ලෙස ඉදිරියට",
  "Continue as a transporter": "ප්‍රවාහකයෙකු ලෙස ඉදිරියට",
  "Continue this draft": "මෙම කෙටුම්පත දිගටම කරන්න",
  "Continue without internet": "අන්තර්ජාලය නැතිව ඉදිරියට යන්න",
  "Create account": "ගිණුම සාදන්න",
  "Create an account": "ගිණුමක් සාදන්න",
  "Crop": "බෝගය",
  "Dambulla market average · guidance only": "දඹුල්ල වෙළඳපොළ සාමාන්‍යය · මඟපෙන්වීමක් පමණි",
  "Dambulla market average. Guidance only — buyers may offer more or less.": "දඹුල්ල වෙළඳපොළ සාමාන්‍යය. මඟපෙන්වීමක් පමණි — ගැනුම්කරුවන් වැඩියෙන් හෝ අඩුවෙන් දීමනා කළ හැක.",
  "Dambulla market average. Guidance only — not a guaranteed price.": "දඹුල්ල වෙළඳපොළ සාමාන්‍යය. මඟපෙන්වීමක් පමණි — සහතික මිලක් නොවේ.",
  "Daughter": "දියණිය",
  "Declining refunds the buyer in full. It does not affect your rating.": "ප්‍රතික්ෂේප කිරීමෙන් ගැනුම්කරුට සම්පූර්ණ මුදල ආපසු ලැබේ. එය ඔබේ ශ්‍රේණිගත කිරීමට බලපාන්නේ නැත.",
  "Delete": "මකන්න",
  "Delete this draft": "මෙම කෙටුම්පත මකන්න",
  "Delete this draft?": "මෙම කෙටුම්පත මකන්නද?",
  "Deliver to (town or area)": "භාර දිය යුතු ස්ථානය (නගරය හෝ ප්‍රදේශය)",
  "Deliver to {place}": "{place} වෙත භාර දීමට",
  "Delivered": "භාර දුන්නා",
  "Delivered. You are paid when {buyer} confirms, within 2 hours of arrival.": "භාර දුන්නා. පැමිණ පැය 2ක් ඇතුළත {buyer} තහවුරු කළ විට ඔබට ගෙවයි.",
  "Delivery to {to}": "{to} වෙත භාරදීම",
  "Delivery · {id}": "භාරදීම · {id}",
  "Done": "නිම විය",
  "Download agreement": "ගිවිසුම බාගන්න",
  "Draft": "කෙටුම්පත",
  "Drafts ({n})": "කෙටුම්පත් ({n})",
  "Earned this week": "මේ සතියේ උපයා ගත්",
  "Edit": "සංස්කරණය",
  "Editable": "වෙනස් කළ හැක",
  "Ends in {time}": "{time} කින් අවසන්",
  "Enter a name.": "නමක් ඇතුළත් කරන්න.",
  "Enter code": "කේතය ඇතුළත් කරන්න",
  "Enter the account number.": "ගිණුම් අංකය ඇතුළත් කරන්න.",
  "Enter the bank.": "බැංකුව ඇතුළත් කරන්න.",
  "Enter the farmer’s own number. The account and every payment belong to that number, whoever is holding the phone.": "ගොවියාගේම අංකය ඇතුළත් කරන්න. දුරකථනය කා අත තිබුණත් ගිණුම සහ සෑම ගෙවීමක්ම එම අංකයට අයත් වේ.",
  "Enter the helper’s name.": "උදව්කරුගේ නම ඇතුළත් කරන්න.",
  "Enter the mobile money number.": "ජංගම මුදල් අංකය ඇතුළත් කරන්න.",
  "Enter your village or area.": "ඔබේ ගම හෝ ප්‍රදේශය ඇතුළත් කරන්න.",
  "Every offer shows what you receive after fees": "සෑම දීමනාවකම ගාස්තු අඩු කළ පසු ඔබට ලැබෙන මුදල පෙන්වයි",
  "Everything entered so far is saved on this account. Step {n} of {total}, saved {time} by {name}. Opening the app on any phone continues from here.": "මෙතෙක් ඇතුළත් කළ සියල්ල මෙම ගිණුමේ සුරැකී ඇත. පියවර {n} / {total}, {time} ට {name} විසින් සුරැකිණි. ඕනෑම දුරකථනයකින් යෙදුම විවෘත කළ විට මෙතැනින් ඉදිරියට යයි.",
  "Everything entered so far is saved on this account. Step {n} of {total}, saved {time}. Opening the app on any phone continues from here.": "මෙතෙක් ඇතුළත් කළ සියල්ල මෙම ගිණුමේ සුරැකී ඇත. පියවර {n} / {total}, {time} ට සුරැකිණි. ඕනෑම දුරකථනයකින් යෙදුම විවෘත කළ විට මෙතැනින් ඉදිරියට යයි.",
  "Expected {date}": "අපේක්ෂිත දිනය {date}",
  "Failed": "අසාර්ථකයි",
  "Farmer": "ගොවියා",
  "Farmer accepted": "ගොවියා පිළිගත්තා",
  "Farmer and transporter notified": "ගොවියාට සහ ප්‍රවාහකයාට දැනුම් දුන්නා",
  "Farmer confirms": "ගොවියා තහවුරු කරයි",
  "Farmer receives after fees": "ගාස්තු අඩු කළ පසු ගොවියාට ලැබේ",
  "Farmer receives {net} by {date}": "ගොවියාට {date} වන විට {net} ලැබේ",
  "Farmers, buyers and transporters in one market — with the price agreed before collection.": "ගොවීන්, ගැනුම්කරුවන් සහ ප්‍රවාහකයන් එකම වෙළඳපොළක — එකතු කිරීමට පෙර මිල එකඟ වී.",
  "Farmer’s full name": "ගොවියාගේ සම්පූර්ණ නම",
  "Field officer": "ක්ෂේත්‍ර නිලධාරී",
  "Field officer, Matale": "ක්ෂේත්‍ර නිලධාරී, මාතලේ",
  "Final weight at collection": "එකතු කිරීමේදී අවසාන බර",
  "Finished": "අවසන්",
  "Fixed": "ස්ථිරයි",
  "For the {kg} kg that arrived in good condition": "හොඳ තත්ත්වයෙන් පැමිණි {kg} kg සඳහා",
  "For {kg} kg of {total} kg · decided by {when}": "{total} kg න් {kg} kg සඳහා · {when} වන විට තීරණය කෙරේ",
  "For {time}": "{time} සඳහා",
  "FriMi": "FriMi",
  "Full name": "සම්පූර්ණ නම",
  "Get paid to your own account, even on a shared phone": "බෙදාගත් දුරකථනයක වුවද ඔබේම ගිණුමට ගෙවීම් ලබන්න",
  "Go back to offers": "දීමනා වෙත ආපසු",
  "Good afternoon": "සුබ දහවලක්",
  "Good evening": "සුබ සන්ධ්‍යාවක්",
  "Good morning": "සුබ උදෑසනක්",
  "Grade": "ශ්‍රේණිය",
  "Grade A": "A ශ්‍රේණිය",
  "Grade A: clean, even size, no damage. Buyers pay more for Grade A and can reject produce that does not match.": "A ශ්‍රේණිය: පිරිසිදු, ඒකාකාර ප්‍රමාණය, හානි නැත. A ශ්‍රේණියට ගැනුම්කරුවන් වැඩි මිලක් ගෙවන අතර ගැළපෙන්නේ නැති අස්වැන්න ප්‍රතික්ෂේප කළ හැක.",
  "Grade B": "B ශ්‍රේණිය",
  "Grade B: minor marks and mixed sizes. Most shops and hotels buy Grade B.": "B ශ්‍රේණිය: සුළු පැල්ලම් සහ මිශ්‍ර ප්‍රමාණ. බොහෝ කඩ සහ හෝටල් B ශ්‍රේණිය මිලදී ගනී.",
  "Grade C": "C ශ්‍රේණිය",
  "Grade C: visible damage. Bought for processing at a lower price.": "C ශ්‍රේණිය: පෙනෙන හානි. අඩු මිලකට සැකසීම සඳහා මිලදී ගනී.",
  "Grade {grade}": "{grade} ශ්‍රේණිය",
  "Grade {grade} {crop} · Dambulla average, not a guaranteed price": "{grade} ශ්‍රේණියේ {crop} · දඹුල්ල සාමාන්‍යය, සහතික මිලක් නොවේ",
  "Guidance {low}–{high}/kg": "මිල මඟපෙන්වීම {low}–{high}/kg",
  "Guidance: {low}–{high}/kg": "මිල මඟපෙන්වීම: {low}–{high}/kg",
  "Guidance: {low}–{high}/kg for Grade {grade} {crop} this week": "මේ සතියේ {grade} ශ්‍රේණියේ {crop} සඳහා මිල මඟපෙන්වීම: {low}–{high}/kg",
  "Guidance: {low}–{high}/kg this week": "මේ සතියේ මිල මඟපෙන්වීම: {low}–{high}/kg",
  "Happening now": "දැන් සිදුවෙමින්",
  "Harvested": "අස්වනු නෙළූ දිනය",
  "Harvested today": "අද නෙළූ",
  "Harvested {date} ({ago})": "නෙළූයේ {date} ({ago})",
  "Harvested {date} · asked {price}": "අස්වනු නෙළූයේ {date} · ඉල්ලූ මිල {price}",
  "Harvested ≤ 3 days": "දින ≤ 3ක් ඇතුළත නෙළූ",
  "Held": "රඳවා ඇත",
  "Held for 30 minutes, until {time}. Nothing is lost if you pay with a different method.": "මිනිත්තු 30ක්, {time} දක්වා රඳවා ඇත. වෙනත් ක්‍රමයකින් ගෙවුවහොත් කිසිවක් නැති නොවේ.",
  "Helper’s name and number": "උදව්කරුගේ නම සහ අංකය",
  "Hide photos": "ඡායාරූප සඟවන්න",
  "How much": "කොපමණද",
  "How much was affected?": "කොපමණ ප්‍රමාණයකට බලපෑවාද?",
  "How much was missing?": "කොපමණ ප්‍රමාණයක් අඩු වී තිබුණාද?",
  "How much was spoiled?": "කොපමණ ප්‍රමාණයක් නරක් වී තිබුණාද?",
  "How much?": "කොපමණද?",
  "I already have an account": "මට දැනටමත් ගිණුමක් ඇත",
  "I cannot supply this": "මට මෙය සැපයිය නොහැක",
  "I collect and deliver for a fee": "මම ගාස්තුවකට රැගෙන ගොස් භාර දෙමි",
  "I grow produce and want to sell it": "මම අස්වැන්න වගා කර විකිණීමට කැමතියි",
  "I want to buy produce": "මට අස්වැන්න මිලදී ගැනීමට අවශ්‍යයි",
  "Identity checked in person by a {who}, {date}.": "{date} දින {who} විසින් පෞද්ගලිකව අනන්‍යතාව පරීක්ෂා කළා.",
  "If no offer comes in 2 days": "දින 2කින් දීමනාවක් නොලැබුණොත්",
  "If no one disputes within 24 hours, {amount} for {kg} kg is refunded automatically.": "පැය 24ක් ඇතුළත කිසිවෙකු විරුද්ධ නොවුවහොත්, {kg} kg සඳහා {amount} ස්වයංක්‍රීයව ආපසු ගෙවයි.",
  "If the weight is wrong": "බර වැරදි නම්",
  "If you grow and also deliver for other people, choose Farmer now and add Transporter later. A field officer can also set this up with you.": "ඔබ වගා කරන අතරම අන් අයට ප්‍රවාහනයද කරන්නේ නම්, දැන් ගොවියා තෝරා පසුව ප්‍රවාහකයා එක් කරන්න. ක්ෂේත්‍ර නිලධාරියෙකුටද ඔබ සමඟ මෙය සකස් කළ හැක.",
  "If you sell all {kg} kg at {price}": "සියලු {kg} kg {price} ට විකුණුවහොත්",
  "In progress": "සිදුවෙමින්",
  "It arrived late": "එය ප්‍රමාද වී පැමිණියා",
  "It may have been withdrawn or already accepted.": "එය ඉවත් කර හෝ දැනටමත් පිළිගෙන තිබිය හැක.",
  "It may have sold. Search again for similar produce.": "එය විකිණී තිබිය හැක. සමාන අස්වැන්නක් නැවත සොයන්න.",
  "Its status is “{status}”.": "එහි තත්ත්වය “{status}”.",
  "Job not found": "රැකියාව හමු නොවීය",
  "Jobs near you": "ඔබ අසල රැකියා",
  "Keep it": "තබා ගන්න",
  "Keep waiting": "තව රැඳී සිටින්න",
  "Keep {kg} kg": "{kg} kg තබා ගන්න",
  "Last attempt failed": "අවසන් උත්සාහය අසාර්ථකයි",
  "Leeks": "ලීක්ස්",
  "List new produce": "නව අස්වැන්නක් ලැයිස්තුගත කරන්න",
  "List produce": "අස්වැන්න ලැයිස්තුගත කරන්න",
  "List what you have ready and buyers will send offers.": "ඔබ සතුව සූදානම් දේ ලැයිස්තුගත කරන්න, ගැනුම්කරුවන් දීමනා එවනු ඇත.",
  "List what you have ready to sell. Buyers see your crop, grade, quantity and harvest date, and send you offers.": "විකිණීමට සූදානම් දේ ලැයිස්තුගත කරන්න. ගැනුම්කරුවන් ඔබේ බෝගය, ශ්‍රේණිය, ප්‍රමාණය සහ අස්වනු දිනය දැක ඔබට දීමනා එවයි.",
  "List your crop, grade, quantity and harvest date": "ඔබේ බෝගය, ශ්‍රේණිය, ප්‍රමාණය සහ අස්වනු දිනය ලැයිස්තුගත කරන්න",
  "Live": "සජීවී",
  "Live ({n})": "සජීවී ({n})",
  "Loading…": "පූරණය වෙමින්…",
  "Lorry booked": "ලොරිය වෙන් කළා",
  "Lorry collects your {crop}": "ලොරිය ඔබේ {crop} රැගෙන යයි",
  "Lower asking price": "ඉල්ලුම් මිල අඩු කරන්න",
  "Lower price": "මිල අඩු කරන්න",
  "Lowering your asking price to {price}/kg would put you at the middle of this week’s guidance range. You would receive about {amount} after fees.": "ඔබේ ඉල්ලුම් මිල {price}/kg දක්වා අඩු කළහොත් මේ සතියේ මිල මඟපෙන්වීම් පරාසයේ මැදට පැමිණේ. ගාස්තු අඩු කළ පසු ඔබට ආසන්න වශයෙන් {amount} ලැබේ.",
  "Mark delivered": "භාර දුන් බව සලකුණු කරන්න",
  "Mixed": "මිශ්‍ර",
  "Mobile money": "ජංගම මුදල්",
  "Mobile money ••••{last4}": "ජංගම මුදල් ••••{last4}",
  "Mobile number": "ජංගම දුරකථන අංකය",
  "Mobile wallet · instant": "ජංගම පසුම්බිය · ක්ෂණිකව",
  "Money": "මුදල්",
  "Money is held until delivery": "භාර දෙන තුරු මුදල් රඳවා තබයි",
  "Money is paid to {name} only.": "මුදල් ගෙවන්නේ {name}ට පමණි.",
  "Most buyers search for produce harvested within 3 days. {crop} harvested {day} appear in those results until {until}.": "බොහෝ ගැනුම්කරුවන් සොයන්නේ දින 3ක් ඇතුළත නෙළූ අස්වැන්නයි. {day} නෙළූ {crop} {until} දක්වා එම ප්‍රතිඵලවල පෙනේ.",
  "My jobs": "මගේ රැකියා",
  "My listings": "මගේ දැන්වීම්",
  "Name": "නම",
  "Needs your answer": "ඔබේ පිළිතුර අවශ්‍යයි",
  "New asking price": "නව ඉල්ලුම් මිල",
  "New jobs appear here as soon as a farmer accepts an offer or an order.": "ගොවියෙකු දීමනාවක් හෝ ඇණවුමක් පිළිගත් වහාම නව රැකියා මෙහි පෙනේ.",
  "New listing": "නව දැන්වීම",
  "New offer": "නව දීමනාව",
  "New order": "නව ඇණවුම",
  "New order — already paid": "නව ඇණවුම — දැනටමත් ගෙවා ඇත",
  "New to the app? Enter your number — we set up your account after the code.": "යෙදුමට අලුත්ද? ඔබේ අංකය ඇතුළත් කරන්න — කේතයෙන් පසු අපි ඔබේ ගිණුම සකසමු.",
  "Next": "ඊළඟ",
  "Next scheduled": "ඊළඟ සැලසුම",
  "No SMS after 2 minutes? Call 0112 000 000, or ask any registered field officer to sign you in at the collection centre.": "මිනිත්තු 2කින් SMS නොලැබුණාද? 0112 000 000 අමතන්න, නැතහොත් එකතු කිරීමේ මධ්‍යස්ථානයේදී ලියාපදිංචි ක්ෂේත්‍ර නිලධාරියෙකුගෙන් ඔබව පිවිසවීමට ඉල්ලන්න.",
  "No drafts.": "කෙටුම්පත් නැත.",
  "No internet connection": "අන්තර්ජාල සම්බන්ධතාවක් නැත",
  "No internet connection. Move to an area with signal and try again.": "අන්තර්ජාල සම්බන්ධතාවක් නැත. සංඥා ඇති ස්ථානයකට ගොස් නැවත උත්සාහ කරන්න.",
  "No internet connection. Nothing has been lost — try again when you have signal.": "අන්තර්ජාල සම්බන්ධතාවක් නැත. කිසිවක් නැති වී නැත — සංඥා ඇති විට නැවත උත්සාහ කරන්න.",
  "No live listings": "සජීවී දැන්වීම් නැත",
  "No money has left your account. The reason given was “{reason}”.": "ඔබේ ගිණුමෙන් කිසිදු මුදලක් අඩු වී නැත. දුන් හේතුව “{reason}”.",
  "No offers yet": "තවම දීමනා නැත",
  "No offers yet · listed {when}": "තවම දීමනා නැත · ලැයිස්තුගත කළේ {when}",
  "No open jobs right now": "දැනට විවෘත රැකියා නැත",
  "No orders yet": "තවම ඇණවුම් නැත",
  "No other fee is taken at collection or at payment. If the weight recorded at collection differs from {kg} kg, you are asked to agree before anything is paid.": "එකතු කිරීමේදී හෝ ගෙවීමේදී වෙනත් ගාස්තුවක් අය නොකරයි. එකතු කිරීමේදී සටහන් වන බර {kg} kg ට වඩා වෙනස් නම්, කිසිවක් ගෙවීමට පෙර ඔබේ එකඟතාව විමසනු ලැබේ.",
  "No past purchases": "පෙර මිලදී ගැනීම් නැත",
  "No payments yet.": "තවම ගෙවීම් නැත.",
  "No weight record for this job": "මෙම රැකියාවට බර වාර්තාවක් නැත",
  "No {crop} harvested today": "අද නෙළූ {crop} නැත",
  "No {crop} matching these filters": "මෙම පෙරහන්වලට ගැළපෙන {crop} නැත",
  "Not getting the SMS?": "SMS ලැබෙන්නේ නැද්ද?",
  "Not published": "ප්‍රකාශ කර නැත",
  "Not sure which one?": "කුමක්දැයි විශ්වාස නැද්ද?",
  "Not verified": "තහවුරු කර නැත",
  "Not yet": "තවම නැත",
  "Nothing else yet. Listings and payments appear here.": "තවම වෙන කිසිවක් නැත. දැන්වීම් සහ ගෙවීම් මෙහි පෙනේ.",
  "Nothing live right now.": "දැනට සජීවී කිසිවක් නැත.",
  "Nothing matches these filters": "මෙම පෙරහන්වලට ගැළපෙන කිසිවක් නැත",
  "Nothing needs your decision today.": "අද ඔබේ තීරණයක් අවශ්‍ය කිසිවක් නැත.",
  "Nothing sold yet.": "තවම කිසිවක් විකුණා නැත.",
  "Nothing was charged.": "කිසිදු මුදලක් අය නොකළා.",
  "Nothing yet. Money appears here once you accept an offer.": "තවම කිසිවක් නැත. ඔබ දීමනාවක් පිළිගත් පසු මුදල් මෙහි පෙනේ.",
  "Now fixed — cannot change": "දැන් ස්ථිරයි — වෙනස් කළ නොහැක",
  "Offer agreed": "දීමනාව එකඟ විය",
  "Offer for all {kg} kg": "සියලු {kg} kg සඳහා දීමනාව",
  "Offer sent": "දීමනාව යැවිණි",
  "Offer total": "දීමනා මුළු මුදල",
  "Offer total {total}, platform fee {fee}": "දීමනා මුළු මුදල {total}, වේදිකා ගාස්තුව {fee}",
  "Offers": "දීමනා",
  "Offers arrive on produce you have listed.": "දීමනා ලැබෙන්නේ ඔබ ලැයිස්තුගත කළ අස්වැන්නටයි.",
  "Offers shown were saved earlier. You cannot accept one until you are back online.": "පෙන්වන දීමනා කලින් සුරැකි ඒවායි. නැවත සම්බන්ධ වන තුරු එකක් පිළිගත නොහැක.",
  "On the way": "මඟ දිගේ",
  "On the way to you": "ඔබ වෙත එමින්",
  "Only the last 4 digits are shown in the app.": "යෙදුමේ පෙන්වන්නේ අවසාන ඉලක්කම් 4 පමණි.",
  "Only {name} can change this — it needs a code sent to {phone}.": "මෙය වෙනස් කළ හැක්කේ {name}ට පමණි — ඒ සඳහා {phone} වෙත එවන කේතයක් අවශ්‍යයි.",
  "Open": "විවෘතයි",
  "Open jobs": "විවෘත රැකියා",
  "Order": "ඇණවුම",
  "Order cancelled": "ඇණවුම අවලංගු කළා",
  "Order held 4 hours while it clears": "මුදල් පැමිණෙන තුරු පැය 4ක් ඇණවුම රඳවා තබයි",
  "Order not found": "ඇණවුම හමු නොවීය",
  "Order placed and paid": "ඇණවුම කර ගෙවා ඇත",
  "Other crop": "වෙනත් බෝගයක්",
  "Other family": "වෙනත් පවුලේ අය",
  "Paid": "ගෙවා ඇත",
  "Paid by buyer": "ගැනුම්කරු ගෙවයි",
  "Paid by {date} — 7 days after collection": "{date} වන විට ගෙවයි — එකතු කිරීමෙන් දින 7කට පසු",
  "Paid into your account": "ඔබේ ගිණුමට ගෙවා ඇත",
  "Paid on the day of collection": "එකතු කරන දිනයේම ගෙවයි",
  "Paid out only once produce is confirmed": "අස්වැන්න තහවුරු කළ පසු පමණක් ගෙවයි",
  "Paid through {method} · we never see or store your card number": "{method} හරහා ගෙවයි · අපි කිසිවිටෙක ඔබේ කාඩ්පත් අංකය දකින්නේවත් ගබඩා කරන්නේවත් නැත",
  "Part of the order was spoiled": "ඇණවුමේ කොටසක් නරක් වී තිබුණා",
  "Pay another way": "වෙනත් ක්‍රමයකින් ගෙවන්න",
  "Pay in 7 days": "දින 7කින් ගෙවන්න",
  "Pay into": "ගෙවිය යුත්තේ",
  "Pay on collection": "එකතු කරන විට ගෙවන්න",
  "Pay with": "ගෙවන ක්‍රමය",
  "Pay {amount} with {method}": "{method} මඟින් {amount} ගෙවන්න",
  "Payment": "ගෙවීම",
  "Payment expected": "අපේක්ෂිත ගෙවීම",
  "Payment history": "ගෙවීම් ඉතිහාසය",
  "Payment is held while it is checked. You will see the buyer’s photos and can respond within 24 hours.": "පරීක්ෂා කරන අතරතුර ගෙවීම රඳවා තබයි. ගැනුම්කරුගේ ඡායාරූප ඔබට පෙනෙන අතර පැය 24ක් ඇතුළත ප්‍රතිචාර දැක්විය හැක.",
  "Payment is held — not cancelled": "ගෙවීම රඳවා ඇත — අවලංගු කර නැත",
  "Payment not completed": "ගෙවීම සම්පූර්ණ නොවීය",
  "Payment received": "ගෙවීම ලැබුණා",
  "Payment released": "ගෙවීම නිදහස් කළා",
  "Payments go to the farmer only": "ගෙවීම් යන්නේ ගොවියාට පමණි",
  "Pending": "බලාපොරොත්තුවෙන්",
  "Photograph the load": "තොගය ඡායාරූප ගන්න",
  "Pick-up is the next morning. Have it packed and weighed.": "රැගෙන යාම හෙට උදේ. ඇසුරුම් කර කිරා තබන්න.",
  "Placed": "ඇණවුම් කළා",
  "Platform fee": "වේදිකා ගාස්තුව",
  "Platform fee (3%)": "වේදිකා ගාස්තුව (3%)",
  "Platform fee ({pct}%)": "වේදිකා ගාස්තුව ({pct}%)",
  "Price": "මිල",
  "Price agreed": "එකඟ වූ මිල",
  "Price and review": "මිල සහ සමාලෝචනය",
  "Price {price} · {kg} kg · fee {fee}": "මිල {price} · {kg} kg · ගාස්තුව {fee}",
  "Price: {price}": "මිල: {price}",
  "Problem reported": "ගැටලුවක් වාර්තා කළා",
  "Produce": "අස්වැන්න",
  "Produce you buy appears here, with its delivery and your payment status.": "ඔබ මිලදී ගන්නා අස්වැන්න, එහි භාරදීම සහ ඔබේ ගෙවීම් තත්ත්වය සමඟ මෙහි පෙනේ.",
  "Publish listing": "දැන්වීම ප්‍රකාශ කරන්න",
  "Quantity": "ප්‍රමාණය",
  "Received": "ලැබුණා",
  "Received and paid": "ලැබී ගෙවා ඇත",
  "Received this month": "මෙම මාසයේ ලැබුණු",
  "Record weight and photos at handover so nothing is disputed": "කිසිදු විවාදයක් නොවීමට භාරදීමේදී බර සහ ඡායාරූප සටහන් කරන්න",
  "Recorded on the day — you confirm it before payment": "එදිනම සටහන් කෙරේ — ගෙවීමට පෙර ඔබ එය තහවුරු කරයි",
  "Recorded {kg} kg · you measured {mine} kg": "සටහන් කළේ {kg} kg · ඔබ මැන්නේ {mine} kg",
  "Refund decided": "ආපසු ගෙවීම තීරණය විය",
  "Refund requested": "ඉල්ලූ ආපසු ගෙවීම",
  "Released to {name}. Thank you.": "{name}ට නිදහස් කළා. ස්තූතියි.",
  "Remove": "ඉවත් කරන්න",
  "Remove this listing?": "මෙම දැන්වීම ඉවත් කරන්නද?",
  "Report a problem": "ගැටලුවක් වාර්තා කරන්න",
  "Report sent": "වාර්තාව යැවිණි",
  "Reservation ended": "වෙන් කිරීම අවසන්",
  "Resolved": "විසඳිණි",
  "Retry": "නැවත උත්සාහ කරන්න",
  "Review": "සමාලෝචනය",
  "Review agreement": "ගිවිසුම සමාලෝචනය",
  "Review listing": "දැන්වීම සමාලෝචනය",
  "Rice": "සහල්",
  "Rs / kg": "රු. / kg",
  "Save as draft": "කෙටුම්පතක් ලෙස සුරකින්න",
  "Save price": "මිල සුරකින්න",
  "Save weight and photos": "බර සහ ඡායාරූප සුරකින්න",
  "Save where money goes": "මුදල් යන තැන සුරකින්න",
  "Saved": "සුරැකිණි",
  "Saved automatically. You can stop and come back.": "ස්වයංක්‍රීයව සුරැකේ. ඔබට නතර කර නැවත පැමිණිය හැක.",
  "Saved information. Accepting needs internet.": "සුරැකි තොරතුරු. පිළිගැනීමට අන්තර්ජාලය අවශ්‍යයි.",
  "Saved information. Paying needs internet.": "සුරැකි තොරතුරු. ගෙවීමට අන්තර්ජාලය අවශ්‍යයි.",
  "Saved jobs — accepting one needs internet.": "සුරැකි රැකියා — එකක් පිළිගැනීමට අන්තර්ජාලය අවශ්‍යයි.",
  "Saved {time} by {name} · step {n} of 4": "{time} ට {name} විසින් සුරැකිණි · පියවර {n} / 4",
  "Saved · may have changed": "සුරැකි · වෙනස් වී තිබිය හැක",
  "Saved — you can stop here": "සුරැකිණි — ඔබට මෙතැනින් නතර කළ හැක",
  "Search by crop, quantity, harvest date and delivery area": "බෝගය, ප්‍රමාණය, අස්වනු දිනය සහ භාරදීමේ ප්‍රදේශය අනුව සොයන්න",
  "Search produce": "අස්වැන්න සොයන්න",
  "See collection and payout": "එකතු කිරීම සහ ගෙවීම බලන්න",
  "See jobs near you with the fee before you accept": "පිළිගැනීමට පෙර ගාස්තුව සමඟ ඔබ අසල රැකියා බලන්න",
  "See offers": "දීමනා බලන්න",
  "See the farmer’s verification and rating before you pay": "ගෙවීමට පෙර ගොවියාගේ තහවුරු කිරීම සහ ශ්‍රේණිගත කිරීම බලන්න",
  "See the order": "ඇණවුම බලන්න",
  "See the problem report": "ගැටලු වාර්තාව බලන්න",
  "Seen by {n} buyers": "ගැනුම්කරුවන් {n} දෙනෙක් බැලුවා",
  "Seen by {n} buyers · best offer ends in {time}": "ගැනුම්කරුවන් {n} දෙනෙක් බැලුවා · හොඳම දීමනාව {time} කින් අවසන්",
  "Sell direct. Buy fresh.": "කෙළින්ම විකුණන්න. නැවුම්ව මිලදී ගන්න.",
  "Seller: {farmer} · Buyer: {buyer}": "විකුණුම්කරු: {farmer} · ගැනුම්කරු: {buyer}",
  "Send": "යවන්න",
  "Send a new code": "නව කේතයක් යවන්න",
  "Send code": "කේතය යවන්න",
  "Send offer": "දීමනාව යවන්න",
  "Send report": "වාර්තාව යවන්න",
  "Send the code again in {clock}": "{clock} කින් කේතය නැවත යවන්න",
  "Sent to {phone}": "{phone} වෙත යැවිණි",
  "Shop": "කඩය",
  "Show produce from the last 3 days": "පසුගිය දින 3 අස්වැන්න පෙන්වන්න",
  "Sign in": "පිවිසෙන්න",
  "Sign out": "ඉවත් වන්න",
  "Sign-in by SMS is switched off for this number’s country. It needs turning on in the Firebase console.": "මෙම අංකයේ රටට SMS පිවිසුම අක්‍රියයි. එය Firebase console හි සක්‍රිය කළ යුතුය.",
  "Sign-in is locked for 15 minutes.": "පිවිසුම මිනිත්තු 15කට අගුළු දමා ඇත.",
  "Sign-in locks for 15 minutes. Call 0112 000 000 or ask a field officer — no money or listing is affected.": "පිවිසුම මිනිත්තු 15කට අගුළු වැටේ. 0112 000 000 අමතන්න හෝ ක්ෂේත්‍ර නිලධාරියෙකුගෙන් විමසන්න — කිසිදු මුදලකට හෝ දැන්වීමකට බලපෑමක් නැත.",
  "Sold": "විකුණා ඇත",
  "Sold ({n})": "විකුණූ ({n})",
  "Someone helping the farmer": "ගොවියාට උදව් කරන කෙනෙක්",
  "Something else": "වෙනත් දෙයක්",
  "Son": "පුතා",
  "Sorted by what you receive — highest first": "ඔබට ලැබෙන මුදල අනුව — වැඩිම මුලින්",
  "Sri Lanka produce market": "ශ්‍රී ලංකා අස්වනු වෙළඳපොළ",
  "Status": "තත්ත්වය",
  "Step {n} of {total}": "පියවර {n} / {total}",
  "Switch from the top of every screen": "සෑම තිරයකම ඉහළින් මාරු කරන්න",
  "Take another photo": "තවත් ඡායාරූපයක් ගන්න",
  "Take photo": "ඡායාරූපයක් ගන්න",
  "Tap Farmer, Buyer or Transporter. Nothing is final — you can change this afterwards in Account.": "ගොවියා, ගැනුම්කරු හෝ ප්‍රවාහකයා ඔබන්න. කිසිවක් අවසාන නොවේ — පසුව ගිණුමේදී වෙනස් කළ හැක.",
  "Tap to switch": "මාරු වීමට ඔබන්න",
  "Tap “Weight is wrong” and enter the weight you measured. Payment is held — not cancelled — until you and {buyer} agree. Most weight questions are settled within 1 working day.": "“බර වැරදියි” ඔබා ඔබ මැන්න බර ඇතුළත් කරන්න. ඔබ සහ {buyer} එකඟ වන තුරු ගෙවීම රඳවා තබයි — අවලංගු නොකරයි. බොහෝ බර ගැටලු වැඩ කරන දින 1ක් ඇතුළත විසඳේ.",
  "That code has expired. Send a new code.": "එම කේතය කල් ඉකුත් වී ඇත. නව කේතයක් යවන්න.",
  "That code was not correct": "එම කේතය නිවැරදි නොවේ",
  "That did not work ({code}). Try again.": "එය සාර්ථක නොවීය ({code}). නැවත උත්සාහ කරන්න.",
  "The 30 minutes have passed. The produce may still be available — try paying again.": "මිනිත්තු 30 ඉකුත් විය. අස්වැන්න තවමත් තිබිය හැක — නැවත ගෙවීමට උත්සාහ කරන්න.",
  "The buyer has already paid": "ගැනුම්කරු දැනටමත් ගෙවා ඇත",
  "The buyer reported a problem": "ගැනුම්කරු ගැටලුවක් වාර්තා කළා",
  "The code could not be checked. Check your connection and try again.": "කේතය පරීක්ෂා කළ නොහැකි විය. සම්බන්ධතාව පරීක්ෂා කර නැවත උත්සාහ කරන්න.",
  "The code could not be sent ({code}). Try again in a minute.": "කේතය යැවිය නොහැකි විය ({code}). මිනිත්තුවකින් නැවත උත්සාහ කරන්න.",
  "The code could not be sent. Try again in a minute.": "කේතය යැවිය නොහැකි විය. මිනිත්තුවකින් නැවත උත්සාහ කරන්න.",
  "The farmer signs in with their own number": "ගොවියා තමාගේම අංකයෙන් පිවිසෙයි",
  "The farmer — this is my own phone": "ගොවියා — මෙය මගේම දුරකථනයයි",
  "The helper": "උදව්කරු",
  "The order was short in weight": "ඇණවුමේ බර අඩු විය",
  "The transporter hands over cash at collection and records it in the app.": "ප්‍රවාහකයා එකතු කරන විට මුදල් භාර දී එය යෙදුමේ සටහන් කරයි.",
  "The weight you measured": "ඔබ මැන්න බර",
  "There is no agreement {id} on this account.": "මෙම ගිණුමේ {id} ගිවිසුමක් නැත.",
  "There is no job {id}.": "{id} රැකියාවක් නැත.",
  "There is no order {id} on this account.": "මෙම ගිණුමේ {id} ඇණවුමක් නැත.",
  "There is no order {id}.": "{id} ඇණවුමක් නැත.",
  "These are all the deductions.": "අඩු කිරීම් සියල්ල මේවායි.",
  "They are the farmer’s": "ඔවුන් ගොවියාගේ",
  "They have 24 hours to respond": "ඔවුන්ට ප්‍රතිචාර දැක්වීමට පැය 24ක් ඇත",
  "This build is not registered with Firebase yet (add its SHA fingerprints in the Firebase console).": "මෙම build එක තවම Firebase හි ලියාපදිංචි කර නැත (Firebase console හි SHA fingerprints එක් කරන්න).",
  "This change must be saved within 5 minutes of the code.": "මෙම වෙනස කේතය ලැබී මිනිත්තු 5ක් ඇතුළත සුරැකිය යුතුය.",
  "This job is not linked to a farmer’s agreement, so there is no weight for the farmer to confirm. Mark it delivered from Jobs.": "මෙම රැකියාව ගොවියෙකුගේ ගිවිසුමකට සම්බන්ධ නැති නිසා ගොවියාට තහවුරු කිරීමට බරක් නැත. රැකියා තිරයෙන් භාර දුන් බව සලකුණු කරන්න.",
  "This number is not a Sri Lankan mobile number.": "මෙය ශ්‍රී ලාංකික ජංගම අංකයක් නොවේ.",
  "This number is too long. A Sri Lankan mobile number has 10 digits, starting 07.": "මෙම අංකය දිග වැඩියි. ශ්‍රී ලාංකික ජංගම අංකයක 07 න් ආරම්භ වන ඉලක්කම් 10ක් ඇත.",
  "This number is too short. A Sri Lankan mobile number has 10 digits, starting 07.": "මෙම අංකය කෙටි වැඩියි. ශ්‍රී ලාංකික ජංගම අංකයක 07 න් ආරම්භ වන ඉලක්කම් 10ක් ඇත.",
  "This offer has already been answered": "මෙම දීමනාවට දැනටමත් පිළිතුරු දී ඇත",
  "This offer is no longer available": "මෙම දීමනාව තවදුරටත් නොමැත",
  "This order is reserved but not paid. Pay another way to confirm it.": "මෙම ඇණවුම වෙන් කර ඇති නමුත් ගෙවා නැත. එය තහවුරු කිරීමට වෙනත් ක්‍රමයකින් ගෙවන්න.",
  "This produce is no longer available": "මෙම අස්වැන්න තවදුරටත් නොමැත",
  "Today": "අද",
  "Today only": "අද පමණයි",
  "Today’s SMS limit for the app has been reached. Try again tomorrow, or ask a field officer to sign you in.": "අද දින යෙදුමේ SMS සීමාව ඉක්මවා ඇත. හෙට නැවත උත්සාහ කරන්න, නැතහොත් ක්ෂේත්‍ර නිලධාරියෙකුගෙන් ඔබව පිවිසවීමට ඉල්ලන්න.",
  "Tomato": "තක්කාලි",
  "Too many codes sent to this number. Wait 15 minutes, or ask a field officer to sign you in.": "මෙම අංකයට කේත වැඩි ගණනක් යවා ඇත. මිනිත්තු 15ක් රැඳී සිටින්න, නැතහොත් ක්ෂේත්‍ර නිලධාරියෙකුගෙන් ඔබව පිවිසවීමට ඉල්ලන්න.",
  "Total": "මුළු මුදල",
  "Transport": "ප්‍රවාහනය",
  "Transporter": "ප්‍රවාහකයා",
  "Transporter being booked": "ප්‍රවාහකයෙකු වෙන් කරමින්",
  "Try again": "නැවත උත්සාහ කරන්න",
  "Try another way to pay": "වෙනත් ක්‍රමයකින් ගෙවන්න",
  "Try fewer filters, or ask to be told when new produce is listed.": "පෙරහන් අඩු කරන්න, නැතහොත් නව අස්වැන්නක් ලැයිස්තුගත වූ විට දැනුම් දෙන ලෙස ඉල්ලන්න.",
  "Use": "භාවිත කරන්න",
  "Using now": "දැන් භාවිත කරයි",
  "Using someone else’s phone?": "වෙනත් අයෙකුගේ දුරකථනයක්ද?",
  "Using someone else’s phone? Either choice works — the account stays with the farmer’s own number.": "වෙනත් අයෙකුගේ දුරකථනයක්ද? ඕනෑම තේරීමක් හරි — ගිණුම ගොවියාගේම අංකයට අයත් වේ.",
  "Verified": "තහවුරු කළ",
  "Verified buyer": "තහවුරු කළ ගැනුම්කරු",
  "Verified farmer": "තහවුරු කළ ගොවියා",
  "Verified farmers only": "තහවුරු කළ ගොවීන් පමණි",
  "View photos": "ඡායාරූප බලන්න",
  "Village / collection area": "ගම / එකතු කිරීමේ ප්‍රදේශය",
  "We send a 6-digit code by SMS. Standard SMS charges apply.": "අපි SMS මඟින් ඉලක්කම් 6ක කේතයක් එවන්නෙමු. සාමාන්‍ය SMS ගාස්තු අදාළ වේ.",
  "We send a code to {name}’s number {phone}. Only someone with that phone can continue.": "අපි {name}ගේ අංකය {phone} වෙත කේතයක් එවන්නෙමු. ඉදිරියට යා හැක්කේ එම දුරකථනය ඇති අයෙකුට පමණි.",
  "Wed–Fri this week": "මේ සතියේ බදාදා–සිකුරාදා",
  "Weight actually collected": "සැබවින්ම එකතු කළ බර",
  "Weight collected": "එකතු කළ බර",
  "Weight is wrong": "බර වැරදියි",
  "Weight questioned": "බර ගැන ප්‍රශ්න කෙරිණි",
  "Weight recorded: {kg} kg": "සටහන් කළ බර: {kg} kg",
  "What are you selling?": "ඔබ විකුණන්නේ කුමක්ද?",
  "What do you do?": "ඔබ කරන්නේ කුමක්ද?",
  "What happens next": "ඊළඟට සිදුවන්නේ",
  "What was entered so far will be lost.": "මෙතෙක් ඇතුළත් කළ දේ නැති වේ.",
  "What went wrong?": "වැරදුණේ කුමක්ද?",
  "What you are selling": "ඔබ විකුණන දේ",
  "What you do": "ඔබ කරන දේ",
  "When and where": "කවදා සහ කොතැනද",
  "Where it goes": "මුදල් යන තැන",
  "Where money goes": "මුදල් යන තැන",
  "Where should the money go?": "මුදල් යා යුත්තේ කොතැනටද?",
  "Which crop?": "කුමන බෝගයද?",
  "Who holds the phone": "දුරකථනය ඇත්තේ කා අතද",
  "Who is holding this phone?": "මෙම දුරකථනය තිබෙන්නේ කා අතද?",
  "Within 1 working day of release": "නිදහස් කිරීමෙන් වැඩ කරන දින 1ක් ඇතුළත",
  "Within 3 days": "දින 3ක් ඇතුළත",
  "Without internet you can read saved information and make phone calls, but cannot accept offers.": "අන්තර්ජාලය නැතිව සුරැකි තොරතුරු කියවීමට සහ දුරකථන ඇමතුම් ගැනීමට හැකි නමුත් දීමනා පිළිගත නොහැක.",
  "Yesterday": "ඊයේ",
  "You and {buyer} are asked to agree the weight. Most weight questions are settled within 1 working day.": "බර ගැන එකඟ වන ලෙස ඔබෙන් සහ {buyer}ගෙන් ඉල්ලා ඇත. බොහෝ බර ගැටලු වැඩ කරන දින 1ක් ඇතුළත විසඳේ.",
  "You are asking": "ඔබ ඉල්ලන මිල",
  "You are seeing information saved on this phone. It may have changed.": "ඔබ දකින්නේ මෙම දුරකථනයේ සුරැකි තොරතුරුයි. ඒවා වෙනස් වී තිබිය හැක.",
  "You can read this offer, but accepting it needs internet.": "ඔබට මෙම දීමනාව කියවිය හැකි නමුත් පිළිගැනීමට අන්තර්ජාලය අවශ්‍යයි.",
  "You cannot accept an offer while offline. Nothing is lost — the offer is still held for you until {time}.": "නොබැඳි විට දීමනාවක් පිළිගත නොහැක. කිසිවක් නැති වී නැත — දීමනාව {time} දක්වා ඔබ වෙනුවෙන් රඳවා ඇත.",
  "You cannot accept an offer while offline. Nothing is lost — the offer is still held for you.": "නොබැඳි විට දීමනාවක් පිළිගත නොහැක. කිසිවක් නැති වී නැත — දීමනාව තවමත් ඔබ වෙනුවෙන් රඳවා ඇත.",
  "You confirm or report": "ඔබ තහවුරු කරන්න හෝ වාර්තා කරන්න",
  "You entered {kg} kg. Your other listings were {range} kg. A wrong quantity can lead to a dispute at collection.": "ඔබ ඇතුළත් කළේ {kg} kg. ඔබේ අනෙක් දැන්වීම් {range} kg විය. වැරදි ප්‍රමාණයක් එකතු කිරීමේදී ගැටලුවකට තුඩු දිය හැක.",
  "You have no listings yet": "ඔබට තවම දැන්වීම් නැත",
  "You pay": "ඔබ ගෙවන්නේ",
  "You receive": "ඔබට ලැබේ",
  "You reported the problem": "ඔබ ගැටලුව වාර්තා කළා",
  "You see the price first": "මිල ඔබට මුලින්ම පෙනේ",
  "You set your own fee — no commission is taken from transport": "ඔබේ ගාස්තුව ඔබම තීරණය කරයි — ප්‍රවාහනයෙන් කොමිස් අය නොකරයි",
  "You will receive": "ඔබට ලැබෙනු ඇත",
  "You would receive": "ඔබට ලැබෙනු ඇත",
  "Your details": "ඔබේ විස්තර",
  "Your details and pay": "ඔබේ විස්තර සහ ගෙවීම්",
  "Your listing is live. Offers usually arrive within 2 days.": "ඔබේ දැන්වීම සජීවීයි. දීමනා සාමාන්‍යයෙන් දින 2ක් ඇතුළත ලැබේ.",
  "Your money is held until you confirm": "ඔබ තහවුරු කරන තුරු ඔබේ මුදල් රඳවා තබයි",
  "Your money is held until you confirm the order arrived": "ඇණවුම ලැබුණු බව ඔබ තහවුරු කරන තුරු ඔබේ මුදල් රඳවා තබයි",
  "Your order": "ඔබේ ඇණවුම",
  "Your order is still reserved": "ඔබේ ඇණවුම තවමත් වෙන් කර ඇත",
  "Your orders": "ඔබේ ඇණවුම්",
  "Your phone has no internet connection. Nothing has been lost — your listings and payments are safe.": "ඔබේ දුරකථනයට අන්තර්ජාල සම්බන්ධතාවක් නැත. කිසිවක් නැති වී නැත — ඔබේ දැන්වීම් සහ ගෙවීම් ආරක්ෂිතයි.",
  "Your price": "ඔබේ මිල",
  "Your roles": "ඔබේ භූමිකා",
  "Your {amount} has been refunded to {method}.": "ඔබේ {amount} {method} වෙත ආපසු ගෙවා ඇත.",
  "Your {amount} is held until you confirm the order arrived.": "ඇණවුම ලැබුණු බව ඔබ තහවුරු කරන තුරු ඔබේ {amount} රඳවා තබයි.",
  "Your {amount} stays held — nothing is paid out.": "ඔබේ {amount} රඳවා තබයි — කිසිවක් ගෙවන්නේ නැත.",
  "Your {crop} was listed on {date} and seen by {n} buyers. Offers usually arrive within 2 days.": "ඔබේ {crop} {date} ලැයිස්තුගත කළ අතර ගැනුම්කරුවන් {n} දෙනෙක් බැලුවා. දීමනා සාමාන්‍යයෙන් දින 2ක් ඇතුළත ලැබේ.",
  "accepted": "පිළිගත්තා",
  "after {amount} fees": "ගාස්තු {amount} අඩු කළ පසු",
  "app.tagline": "ගොවියාගෙන් ගැනුම්කරුට",
  "bank transfer": "බැංකු හුවමාරුව",
  "being assigned": "පවරමින්",
  "cash at collection": "එකතු කරන විට මුදලින්",
  "clean, even size, no damage": "පිරිසිදු, ඒකාකාර ප්‍රමාණය, හානි නැත",
  "common.back": "ආපසු",
  "common.continue": "ඉදිරියට",
  "common.next": "ඊළඟ",
  "common.stepOf": "පියවර {n} / {total}",
  "common.tryAgain": "නැවත උත්සාහ කරන්න",
  "eZ Cash": "eZ Cash",
  "eZ Cash or mCash number": "eZ Cash හෝ mCash අංකය",
  "expired": "කල් ඉකුත් විය",
  "fee": "ගාස්තුව",
  "field officer": "ක්ෂේත්‍ර නිලධාරී",
  "insufficient balance": "ශේෂය ප්‍රමාණවත් නැත",
  "minor marks, mixed size": "සුළු පැල්ලම්, මිශ්‍ර ප්‍රමාණ",
  "mobile money ••••{last4}": "ජංගම මුදල් ••••{last4}",
  "nav.account": "ගිණුම",
  "nav.earnings": "ආදායම",
  "nav.home": "මුල් පිටුව",
  "nav.jobs": "රැකියා",
  "nav.listings": "දැන්වීම්",
  "nav.money": "මුදල්",
  "nav.myJob": "මගේ රැකියාව",
  "nav.offers": "දීමනා",
  "nav.orders": "ඇණවුම්",
  "nav.search": "සොයන්න",
  "owner.holder": "දුරකථනය භාවිත කරන්නේ",
  "owner.owner": "ගිණුම් හිමිකරු",
  "owner.rule": "ගෙවීම් ලැබෙන්නේ {owner}ට පමණි. {operator}ට විස්තර ඇතුළත් කළ හැකි නමුත් මුදල් ලබා ගත නොහැක.",
  "pays in 7 days": "දින 7කින් ගෙවයි",
  "pays on collection": "එකතු කරන විට ගෙවයි",
  "pending": "බලාපොරොත්තුවෙන්",
  "rejected": "ප්‍රතික්ෂේප කළා",
  "saved {time}": "{time} ට සුරැකිණි",
  "saved {time} by {name}": "{time} ට {name} විසින් සුරැකිණි",
  "splash.loading": "ඔබගේ ගිණුම පූරණය වෙමින්…",
  "the farmer": "ගොවියා",
  "the transporter": "ප්‍රවාහකයා",
  "today": "අද",
  "transporter": "ප්‍රවාහකයා",
  "transporter being booked": "ප්‍රවාහකයෙකු වෙන් කරමින්",
  "unknown": "නොදන්නා",
  "unknown error": "නොදන්නා දෝෂය",
  "visible damage, for processing": "පෙනෙන හානි, සැකසීම සඳහා",
  "you": "ඔබ",
  "you earn": "ඔබ උපයයි",
  "your bank account": "ඔබේ බැංකු ගිණුම",
  "your price is above the range": "ඔබේ මිල පරාසයට ඉහළින්",
  "your price is above the range.": "ඔබේ මිල පරාසයට ඉහළින්.",
  "your price is below the range": "ඔබේ මිල පරාසයට පහළින්",
  "your price is below the range.": "ඔබේ මිල පරාසයට පහළින්.",
  "your price is inside the range": "ඔබේ මිල පරාසය තුළ",
  "your price is inside the range.": "ඔබේ මිල පරාසය තුළ.",
  "{amount} is held by the platform and paid to you once {buyer} confirms the {crop} arrived.": "{amount} වේදිකාව රඳවා තබා ඇති අතර {crop} ලැබුණු බව {buyer} තහවුරු කළ පසු ඔබට ගෙවයි.",
  "{amount} received": "{amount} ලැබුණා",
  "{amount} released to {name}": "{name}ට {amount} නිදහස් කළා",
  "{buyer} confirmed the order. {amount} is on its way to you.": "{buyer} ඇණවුම තහවුරු කළා. {amount} ඔබ වෙත එමින් පවතී.",
  "{crop} Grade {grade}, {kg} kg": "{crop} {grade} ශ්‍රේණිය, {kg} kg",
  "{crop} is usually picked early and listed the same evening. Widening the harvest window finds produce that is still fresh.": "{crop} සාමාන්‍යයෙන් උදේ නෙළා එදින සවස ලැයිස්තුගත කරයි. අස්වනු කාලය පුළුල් කිරීමෙන් තවමත් නැවුම් අස්වැන්න සොයාගත හැක.",
  "{crop} {kg} kg": "{crop} {kg} kg",
  "{crop} {kg} kg from {farmer} · {amount}": "{farmer}ගෙන් {crop} {kg} kg · {amount}",
  "{crop} {kg} kg to {buyer}": "{crop} {kg} kg {buyer} වෙත",
  "{crop} {kg} kg · deliver to {place}": "{crop} {kg} kg · {place} වෙත භාර දීමට",
  "{crop} {kg} kg · held by the platform until you confirm collection": "{crop} {kg} kg · ඔබ එකතු කිරීම තහවුරු කරන තුරු වේදිකාව රඳවා තබයි",
  "{crop} {kg} kg · listed": "{crop} {kg} kg · ලැයිස්තුගතයි",
  "{crop} {kg} kg · {buyer} · {date} · fee {fee}": "{crop} {kg} kg · {buyer} · {date} · ගාස්තුව {fee}",
  "{crop} {kg} kg · {day} {from}–{to}": "{crop} {kg} kg · {day} {from}–{to}",
  "{crop} {kg} kg · {farmer}": "{crop} {kg} kg · {farmer}",
  "{crop} {kg} kg · {id}": "{crop} {kg} kg · {id}",
  "{crop} {kg} kg · {n} offers": "{crop} {kg} kg · දීමනා {n}",
  "{crop} · Grade {grade}": "{crop} · {grade} ශ්‍රේණිය",
  "{crop} · agreed {kg} kg · {id}": "{crop} · එකඟ වූ {kg} kg · {id}",
  "{crop} · agreed {kg} kg · {name}, {time}": "{crop} · එකඟ වූ {kg} kg · {name}, {time}",
  "{date} · to {where}": "{date} · {where} වෙත",
  "{farmer} is paid only after the {crop} arrives and you accept it. If the order is late, damaged or short, report it within 2 hours of arrival and you are refunded.": "{crop} ලැබී ඔබ එය පිළිගත් පසු පමණක් {farmer}ට ගෙවයි. ඇණවුම ප්‍රමාද, හානි වූ හෝ අඩු නම්, පැමිණ පැය 2ක් ඇතුළත වාර්තා කළ විට ඔබේ මුදල් ආපසු ලැබේ.",
  "{farmer} sees your offer of {price} for all {kg} kg. It stays open for 24 hours.": "සියලු {kg} kg සඳහා {price} ඔබේ දීමනාව {farmer}ට පෙනේ. එය පැය 24ක් විවෘතව පවතී.",
  "{f} filters · {n} results": "පෙරහන් {f} · ප්‍රතිඵල {n}",
  "{helper} can read this page but cannot edit it or receive payment.": "{helper}ට මෙම පිටුව කියවිය හැකි නමුත් සංස්කරණය කිරීමට හෝ ගෙවීම් ලබා ගැනීමට නොහැක.",
  "{kg} kg": "{kg} kg",
  "{kg} kg (you confirmed)": "{kg} kg (ඔබ තහවුරු කළා)",
  "{kg} kg available": "{kg} kg ලබා ගත හැක",
  "{kg} kg less than agreed": "එකඟ වූ ප්‍රමාණයට වඩා {kg} kg අඩුයි",
  "{kg} kg more than agreed": "එකඟ වූ ප්‍රමාණයට වඩා {kg} kg වැඩියි",
  "{kg} kg recorded": "{kg} kg සටහන් විය",
  "{kg} kg × {price}": "{kg} kg × {price}",
  "{method} could not complete the payment": "{method} හට ගෙවීම සම්පූර්ණ කළ නොහැකි විය",
  "{name} and the transporter see your photos today.": "{name}ට සහ ප්‍රවාහකයාට අද ඔබේ ඡායාරූප පෙනේ.",
  "{name} can enter details and read the account, but cannot receive payment or change where money is sent.": "{name}ට විස්තර ඇතුළත් කිරීමට සහ ගිණුම කියවීමට හැකි නමුත් ගෙවීම් ලබා ගැනීමට හෝ මුදල් යවන තැන වෙනස් කිරීමට නොහැක.",
  "{name} can enter details but cannot receive money or change where it is sent.": "{name}ට විස්තර ඇතුළත් කළ හැකි නමුත් මුදල් ලබා ගැනීමට හෝ එය යවන තැන වෙනස් කිරීමට නොහැක.",
  "{name} delivers this order": "{name} මෙම ඇණවුම භාර දෙයි",
  "{name} has confirmed this weight.": "{name} මෙම බර තහවුරු කර ඇත.",
  "{name} has questioned this weight — it is being checked.": "{name} මෙම බර ගැන ප්‍රශ්න කර ඇත — එය පරීක්ෂා කෙරේ.",
  "{name} is asked to confirm it in their app before payment.": "ගෙවීමට පෙර තම යෙදුමෙන් එය තහවුරු කරන ලෙස {name}ගෙන් ඉල්ලා ඇත.",
  "{name} is paid for {kg} kg ({amount} after fee). They confirm this weight before payment.": "{name}ට {kg} kg සඳහා ගෙවයි (ගාස්තුවෙන් පසු {amount}). ගෙවීමට පෙර ඔවුන් මෙම බර තහවුරු කරයි.",
  "{name} sees the weight and your photos in their app and confirms it there. Nothing is paid until they do.": "{name}ට තම යෙදුමෙහි බර සහ ඔබේ ඡායාරූප පෙනෙන අතර එහිදී එය තහවුරු කරයි. ඔවුන් එසේ කරන තුරු කිසිවක් ගෙවන්නේ නැත.",
  "{name} · {kg} kg": "{name} · {kg} kg",
  "{n} days": "දින {n}",
  "{n} days ago": "දින {n}කට පෙර",
  "{n} hours": "පැය {n}",
  "{n} jobs": "රැකියා {n}",
  "{n} minutes": "මිනිත්තු {n}",
  "{n} offers": "දීමනා {n}",
  "{n} offers · best {price}": "දීමනා {n} · හොඳම {price}",
  "{n} past purchases": "පෙර මිලදී ගැනීම් {n}",
  "{n} photos saved at {time}.": "{time} ට ඡායාරූප {n} සුරැකිණි.",
  "{n} photos sent · {time}": "ඡායාරූප {n} යැවිණි · {time}",
  "{n} photos taken at your gate, {time}, by {name}": "{time} ට ඔබේ ගේට්ටුව අසලදී {name} ගත් ඡායාරූප {n}",
  "{n} taken at {name}’s gate, {time}. Photos are time-stamped and cannot be changed later.": "{time} ට {name}ගේ ගේට්ටුව අසල {n}ක් ගත්තා. ඡායාරූපවලට වේලාව සටහන් වී ඇති අතර පසුව වෙනස් කළ නොහැක.",
  "{n} tries left.": "තව උත්සාහ {n}ක් ඉතිරියි.",
  "{n} views · no offers yet": "බැලීම් {n} · තවම දීමනා නැත",
  "{place} · delivers to {to}": "{place} · {to} වෙත භාර දෙයි",
  "{place} · selling since {when}": "{place} · {when} සිට විකුණයි",
  "{place} · {n} open": "{place} · විවෘත {n}",
  "{place} — home garden": "{place} — ගෙවත්ත",
  "{rating} from {n} buyers": "ගැනුම්කරුවන් {n} දෙනෙකුගෙන් {rating}",
  "{time} · {amount} held": "{time} · {amount} රඳවා ඇත",
  "{what} — not finished": "{what} — අවසන් කර නැත",
  "සිංහල or English, any time": "සිංහල හෝ English, ඕනෑම වේලාවක",
};
